name: platedepth
description: Pastel-themed food volume estimation app with native camera and CoreML integration.
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0
  collection: ^1.18.0
  fluttertoast: ^8.2.4
  permission_handler: ^11.3.1
  intl: ^0.19.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
